/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class thesis_ConnectionJNI */

#ifndef _Included_thesis_ConnectionJNI
#define _Included_thesis_ConnectionJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     thesis_ConnectionJNI
 * Method:    openConnection
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)I
 */
JNIEXPORT jint JNICALL Java_thesis_ConnectionJNI_openConnection
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     thesis_ConnectionJNI
 * Method:    closeConnection
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_thesis_ConnectionJNI_closeConnection
  (JNIEnv *, jobject);

/*
 * Class:     thesis_ConnectionJNI
 * Method:    getClassData
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_thesis_ConnectionJNI_getClassData
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
