#!/bin/sh
#
# serialport        Starts spd, the SerialPort daemon.
#
#
# chkconfig: 2345 55 75
# description: spd is the SerialPort server daemon. 
#              The spc utility is used for the status
#              and stop commands.

# Source function library.
. /etc/rc.d/init.d/functions

[ -f /usr/local/bin/spd ] || exit 0
[ -f /usr/local/bin/spc ] || exit 0

RETVAL=0

# See how we were called.
case "$1" in
  start)
	echo -n "Starting SerialPort daemon: "
	daemon /usr/local/bin/spd -D
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/spd
	;;
  stop)
	echo -n "Shutting down serialport daemon: "
	[ -f /var/lock/subsys/spd ] && /usr/local/bin/spc stop
	echo
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/spd
	;;
  status)
	status spd
	RETVAL=$?
	[ -f /var/lock/subsys/spd ] && /usr/local/bin/spc status
	;;
  restart|reload)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  *)
	echo "Usage: serialport {start|stop|status|restart}"
	exit 1
esac

exit $RETVAL

